//
//  ManglingFixtures.swift
//  SwiftDemangleTests
//
//  Examples from swift/test/Demangle/inputs/manglings.txt.
//

enum ManglingFixtures {
    struct Example: Sendable {
        let input: String
        let output: String
    }

    static var validExamples: [Example] {
        examples.filter { $0.input != $0.output }
    }

    static var invalidExamples: [Example] {
        examples.filter { $0.input == $0.output }
    }

    private static let examples: [Example] = [
        .init(input: "_TtBf32_", output: "Builtin.FPIEEE32"),
        .init(input: "_TtBf64_", output: "Builtin.FPIEEE64"),
        .init(input: "_TtBf80_", output: "Builtin.FPIEEE80"),
        .init(input: "_TtBi32_", output: "Builtin.Int32"),
        .init(input: "$sBf32_", output: "Builtin.FPIEEE32"),
        .init(input: "$sBf64_", output: "Builtin.FPIEEE64"),
        .init(input: "$sBf80_", output: "Builtin.FPIEEE80"),
        .init(input: "$sBi32_", output: "Builtin.Int32"),
        .init(input: "_TtBw", output: "Builtin.Word"),
        .init(input: "_TtBO", output: "Builtin.UnknownObject"),
        .init(input: "_TtBo", output: "Builtin.NativeObject"),
        .init(input: "_TtBp", output: "Builtin.RawPointer"),
        .init(input: "_TtBt", output: "Builtin.SILToken"),
        .init(input: "_TtBv4Bi8_", output: "Builtin.Vec4xInt8"),
        .init(input: "_TtBv4Bf16_", output: "Builtin.Vec4xFPIEEE16"),
        .init(input: "_TtBv4Bp", output: "Builtin.Vec4xRawPointer"),
        .init(input: "$sBi8_Bv4_", output: "Builtin.Vec4xInt8"),
        .init(input: "$sBf16_Bv4_", output: "Builtin.Vec4xFPIEEE16"),
        .init(input: "$sBpBv4_", output: "Builtin.Vec4xRawPointer"),
        .init(input: "_TtSa", output: "Swift.Array"),
        .init(input: "_TtSb", output: "Swift.Bool"),
        .init(input: "_TtSc", output: "Swift.UnicodeScalar"),
        .init(input: "_TtSd", output: "Swift.Double"),
        .init(input: "_TtSf", output: "Swift.Float"),
        .init(input: "_TtSi", output: "Swift.Int"),
        .init(input: "_TtSq", output: "Swift.Optional"),
        .init(input: "_TtSS", output: "Swift.String"),
        .init(input: "_TtSu", output: "Swift.UInt"),
        .init(input: "_TtGSPSi_", output: "Swift.UnsafePointer<Swift.Int>"),
        .init(input: "_TtGSpSi_", output: "Swift.UnsafeMutablePointer<Swift.Int>"),
        .init(input: "_TtSV", output: "Swift.UnsafeRawPointer"),
        .init(input: "_TtSv", output: "Swift.UnsafeMutableRawPointer"),
        .init(input: "_TtGSaSS_", output: "[Swift.String]"),
        .init(input: "_TtGSqSS_", output: "Swift.String?"),
        .init(input: "_TtGVs10DictionarySSSi_", output: "[Swift.String : Swift.Int]"),
        .init(input: "_TtVs7CString", output: "Swift.CString"),
        .init(input: "_TtCSo8NSObject", output: "__C.NSObject"),
        .init(input: "_TtO6Monads6Either", output: "Monads.Either"),
        .init(input: "_TtbSiSu", output: "@convention(block) (Swift.Int) -> Swift.UInt"),
        .init(input: "_TtcSiSu", output: "@convention(c) (Swift.Int) -> Swift.UInt"),
        .init(input: "_TtbTSiSc_Su", output: "@convention(block) (Swift.Int, Swift.UnicodeScalar) -> Swift.UInt"),
        .init(input: "_TtcTSiSc_Su", output: "@convention(c) (Swift.Int, Swift.UnicodeScalar) -> Swift.UInt"),
        .init(input: "_TtFSiSu", output: "(Swift.Int) -> Swift.UInt"),
        .init(input: "_TtKSiSu", output: "@autoclosure (Swift.Int) -> Swift.UInt"),
        .init(input: "_TtFSiFScSu", output: "(Swift.Int) -> (Swift.UnicodeScalar) -> Swift.UInt"),
        .init(input: "_TtMSi", output: "Swift.Int.Type"),
        .init(input: "_TtP_", output: "Any"),
        .init(input: "_TtP3foo3bar_", output: "foo.bar"),
        .init(input: "_TtP3foo3barS_3bas_", output: "foo.bar & foo.bas"),
        .init(input: "_TtTP3foo3barS_3bas_PS1__PS1_S_3zimS0___", output: "(foo.bar & foo.bas, foo.bas, foo.bas & foo.zim & foo.bar)"),
        .init(input: "_TtRSi", output: "inout Swift.Int"),
        .init(input: "_TtTSiSu_", output: "(Swift.Int, Swift.UInt)"),
        .init(input: "_TttSiSu_", output: "(Swift.Int, Swift.UInt...)"),
        .init(input: "_TtT3fooSi3barSu_", output: "(foo: Swift.Int, bar: Swift.UInt)"),
        .init(input: "_TturFxx", output: "<A>(A) -> A"),
        .init(input: "_TtuzrFT_T_", output: "<>() -> ()"),
        .init(input: "_Ttu__rFxqd__", output: "<A><A1>(A) -> A1"),
        .init(input: "_Ttu_z_rFxqd0__", output: "<A><><A2>(A) -> A2"),
        .init(input: "_Ttu0_rFxq_", output: "<A, B>(A) -> B"),
        .init(input: "_TtuRxs8RunciblerFxwx5Mince", output: "<A where A: Swift.Runcible>(A) -> A.Mince"),
        .init(input: "_TtuRxle64xs8RunciblerFxwx5Mince", output: "<A where A: _Trivial(64), A: Swift.Runcible>(A) -> A.Mince"),
        .init(input: "_TtuRxlE64_16rFxwx5Mince", output: "<A where A: _Trivial(64, 16)>(A) -> A.Mince"),
        .init(input: "_TtuRxlE64_32xs8RunciblerFxwx5Mince", output: "<A where A: _Trivial(64, 32), A: Swift.Runcible>(A) -> A.Mince"),
        .init(input: "_TtuRxlM64_16rFxwx5Mince", output: "<A where A: _TrivialAtMost(64, 16)>(A) -> A.Mince"),
        .init(input: "_TtuRxle64rFxwx5Mince", output: "<A where A: _Trivial(64)>(A) -> A.Mince"),
        .init(input: "_TtuRxlm64rFxwx5Mince", output: "<A where A: _TrivialAtMost(64)>(A) -> A.Mince"),
        .init(input: "_TtuRxlNrFxwx5Mince", output: "<A where A: _NativeRefCountedObject>(A) -> A.Mince"),
        .init(input: "_TtuRxlRrFxwx5Mince", output: "<A where A: _RefCountedObject>(A) -> A.Mince"),
        .init(input: "_TtuRxlUrFxwx5Mince", output: "<A where A: _UnknownLayout>(A) -> A.Mince"),
        .init(input: "_TtuRxs8RunciblerFxWx5Mince6Quince_", output: "<A where A: Swift.Runcible>(A) -> A.Mince.Quince"),
        .init(input: "_TtuRxs8Runciblexs8FungiblerFxwxPS_5Mince", output: "<A where A: Swift.Runcible, A: Swift.Fungible>(A) -> A.Swift.Runcible.Mince"),
        .init(input: "_TtuRxCs22AbstractRuncingFactoryrFxx", output: "<A where A: Swift.AbstractRuncingFactory>(A) -> A"),
        .init(input: "_TtuRxs8Runciblewx5MincezxrFxx", output: "<A where A: Swift.Runcible, A.Mince == A>(A) -> A"),
        .init(input: "_TtuRxs8RuncibleWx5Mince6Quince_zxrFxx", output: "<A where A: Swift.Runcible, A.Mince.Quince == A>(A) -> A"),
        .init(input: "_Ttu0_Rxs8Runcible_S_wx5Minces8Fungiblew_S0_S1_rFxq_", output: "<A, B where A: Swift.Runcible, B: Swift.Runcible, A.Mince: Swift.Fungible, B.Mince: Swift.Fungible>(A) -> B"),
        .init(input: "_Ttu0_Rx3Foo3BarxCS_3Bas_S0__S1_rT_", output: "<A, B where A: Foo.Bar, A: Foo.Bas, B: Foo.Bar, B: Foo.Bas> ()"),
        .init(input: "_Tv3foo3barSi", output: "foo.bar : Swift.Int"),
        .init(input: "_TF3fooau3barSi", output: "foo.bar.unsafeMutableAddressor : Swift.Int"),
        .init(input: "_TF3foolu3barSi", output: "foo.bar.unsafeAddressor : Swift.Int"),
        .init(input: "_TF3fooaO3barSi", output: "foo.bar.owningMutableAddressor : Swift.Int"),
        .init(input: "_TF3foolO3barSi", output: "foo.bar.owningAddressor : Swift.Int"),
        .init(input: "_TF3fooao3barSi", output: "foo.bar.nativeOwningMutableAddressor : Swift.Int"),
        .init(input: "_TF3foolo3barSi", output: "foo.bar.nativeOwningAddressor : Swift.Int"),
        .init(input: "_TF3fooap3barSi", output: "foo.bar.nativePinningMutableAddressor : Swift.Int"),
        .init(input: "_TF3foolp3barSi", output: "foo.bar.nativePinningAddressor : Swift.Int"),
        .init(input: "_TF3foog3barSi", output: "foo.bar.getter : Swift.Int"),
        .init(input: "_TF3foos3barSi", output: "foo.bar.setter : Swift.Int"),
        .init(input: "_TFC3foo3bar3basfT3zimCS_3zim_T_", output: "foo.bar.bas(zim: foo.zim) -> ()"),
        .init(input: "_TToFC3foo3bar3basfT3zimCS_3zim_T_", output: "@objc foo.bar.bas(zim: foo.zim) -> ()"),
        .init(input: "_TTOFSC3fooFTSdSd_Sd", output: "@nonobjc __C_Synthesized.foo(Swift.Double, Swift.Double) -> Swift.Double"),
        .init(input: "_T03foo3barC3basyAA3zimCAE_tFTo", output: "@objc foo.bar.bas(zim: foo.zim) -> ()"),
        .init(input: "_T0SC3fooS2d_SdtFTO", output: "@nonobjc __C_Synthesized.foo(Swift.Double, Swift.Double) -> Swift.Double"),
        .init(input: "_$s3foo3barC3bas3zimyAaEC_tFTo", output: "@objc foo.bar.bas(zim: foo.zim) -> ()"),
        .init(input: "_$sSC3fooyS2d_SdtFTO", output: "@nonobjc __C_Synthesized.foo(Swift.Double, Swift.Double) -> Swift.Double"),
        .init(input: "_$S3foo3barC3bas3zimyAaEC_tFTo", output: "@objc foo.bar.bas(zim: foo.zim) -> ()"),
        .init(input: "_$SSC3fooyS2d_SdtFTO", output: "@nonobjc __C_Synthesized.foo(Swift.Double, Swift.Double) -> Swift.Double"),
        .init(input: "_$sTA.123", output: "partial apply forwarder with unmangled suffix \".123\""),
        .init(input: "$s4main3fooyySiFyyXEfU_TA.1", output: "partial apply forwarder for closure #1 () -> () in main.foo(Swift.Int) -> () with unmangled suffix \".1\""),
        .init(input: "$s4main8MyStructV3fooyyFAA1XV_Tg5.foo", output: "generic specialization <main.X> of main.MyStruct.foo() -> () with unmangled suffix \".foo\""),
        .init(input: "_TTDFC3foo3bar3basfT3zimCS_3zim_T_", output: "dynamic foo.bar.bas(zim: foo.zim) -> ()"),
        .init(input: "_TF3foooi1pFTCS_3barVS_3bas_OS_3zim", output: "foo.+ infix(foo.bar, foo.bas) -> foo.zim"),
        .init(input: "_TF3foooP1xFTCS_3barVS_3bas_OS_3zim", output: "foo.^ postfix(foo.bar, foo.bas) -> foo.zim"),
        .init(input: "_TFC3foo3barCfT_S0_", output: "foo.bar.__allocating_init() -> foo.bar"),
        .init(input: "_TFC3foo3barcfT_S0_", output: "foo.bar.init() -> foo.bar"),
        .init(input: "_TFC3foo3barD", output: "foo.bar.__deallocating_deinit"),
        .init(input: "_TFC3foo3barZ", output: "foo.bar.__isolated_deallocating_deinit"),
        .init(input: "_TFC3foo3bard", output: "foo.bar.deinit"),
        .init(input: "_TMPC3foo3bar", output: "generic type metadata pattern for foo.bar"),
        .init(input: "_TMnC3foo3bar", output: "nominal type descriptor for foo.bar"),
        .init(input: "_TMmC3foo3bar", output: "metaclass for foo.bar"),
        .init(input: "_TMC3foo3bar", output: "type metadata for foo.bar"),
        .init(input: "_TMfC3foo3bar", output: "full type metadata for foo.bar"),
        .init(input: "_TwalC3foo3bar", output: "allocateBuffer value witness for foo.bar"),
        .init(input: "_TwcaC3foo3bar", output: "assignWithCopy value witness for foo.bar"),
        .init(input: "_TwtaC3foo3bar", output: "assignWithTake value witness for foo.bar"),
        .init(input: "_TwdeC3foo3bar", output: "deallocateBuffer value witness for foo.bar"),
        .init(input: "_TwxxC3foo3bar", output: "destroy value witness for foo.bar"),
        .init(input: "_TwXXC3foo3bar", output: "destroyBuffer value witness for foo.bar"),
        .init(input: "_TwCPC3foo3bar", output: "initializeBufferWithCopyOfBuffer value witness for foo.bar"),
        .init(input: "_TwCpC3foo3bar", output: "initializeBufferWithCopy value witness for foo.bar"),
        .init(input: "_TwcpC3foo3bar", output: "initializeWithCopy value witness for foo.bar"),
        .init(input: "_TwTKC3foo3bar", output: "initializeBufferWithTakeOfBuffer value witness for foo.bar"),
        .init(input: "_TwTkC3foo3bar", output: "initializeBufferWithTake value witness for foo.bar"),
        .init(input: "_TwtkC3foo3bar", output: "initializeWithTake value witness for foo.bar"),
        .init(input: "_TwprC3foo3bar", output: "projectBuffer value witness for foo.bar"),
        .init(input: "_TWVC3foo3bar", output: "value witness table for foo.bar"),
        .init(input: "_TWvdvC3foo3bar3basSi", output: "direct field offset for foo.bar.bas : Swift.Int"),
        .init(input: "_TWvivC3foo3bar3basSi", output: "indirect field offset for foo.bar.bas : Swift.Int"),
        .init(input: "_TWPC3foo3barS_8barrables", output: "protocol witness table for foo.bar : foo.barrable in Swift"),
        .init(input: "_TWaC3foo3barS_8barrableS_", output: "protocol witness table accessor for foo.bar : foo.barrable in foo"),
        .init(input: "_TWlC3foo3barS0_S_8barrableS_", output: "lazy protocol witness table accessor for type foo.bar and conformance foo.bar : foo.barrable in foo"),
        .init(input: "_TWLC3foo3barS0_S_8barrableS_", output: "lazy protocol witness table cache variable for type foo.bar and conformance foo.bar : foo.barrable in foo"),
        .init(input: "_TWGC3foo3barS_8barrableS_", output: "generic protocol witness table for foo.bar : foo.barrable in foo"),
        .init(input: "_TWIC3foo3barS_8barrableS_", output: "instantiation function for generic protocol witness table for foo.bar : foo.barrable in foo"),
        .init(input: "_TWtC3foo3barS_8barrableS_4fred", output: "associated type metadata accessor for fred in foo.bar : foo.barrable in foo"),
        .init(input: "_TWTC3foo3barS_8barrableS_4fredS_6thomas", output: "associated type witness table accessor for fred : foo.thomas in foo.bar : foo.barrable in foo"),
        .init(input: "_TFSCg5greenVSC5Color", output: "__C_Synthesized.green.getter : __C_Synthesized.Color"),
        .init(input: "_TIF1t1fFT1iSi1sSS_T_A_", output: "default argument 0 of t.f(i: Swift.Int, s: Swift.String) -> ()"),
        .init(input: "_TIF1t1fFT1iSi1sSS_T_A0_", output: "default argument 1 of t.f(i: Swift.Int, s: Swift.String) -> ()"),
        .init(input: "_TFSqcfT_GSqx_", output: "Swift.Optional.init() -> A?"),
        .init(input: "_TF21class_bound_protocols32class_bound_protocol_compositionFT1xPS_10ClassBoundS_13NotClassBound__PS0_S1__", output: "class_bound_protocols.class_bound_protocol_composition(x: class_bound_protocols.ClassBound & class_bound_protocols.NotClassBound) -> class_bound_protocols.ClassBound & class_bound_protocols.NotClassBound"),
        .init(input: "_TtZZ", output: "_TtZZ"),
        .init(input: "_TtB", output: "_TtB"),
        .init(input: "_TtBSi", output: "_TtBSi"),
        .init(input: "_TtBx", output: "_TtBx"),
        .init(input: "_TtC", output: "_TtC"),
        .init(input: "_TtT", output: "_TtT"),
        .init(input: "_TtTSi", output: "_TtTSi"),
        .init(input: "_TtQd_", output: "_TtQd_"),
        .init(input: "_TtU__FQo_Si", output: "_TtU__FQo_Si"),
        .init(input: "_TtU__FQD__Si", output: "_TtU__FQD__Si"),
        .init(input: "_TtU___FQ_U____FQd0__T_", output: "_TtU___FQ_U____FQd0__T_"),
        .init(input: "_TtU___FQ_U____FQd_1_T_", output: "_TtU___FQ_U____FQd_1_T_"),
        .init(input: "_TtU___FQ_U____FQ2_T_", output: "_TtU___FQ_U____FQ2_T_"),
        .init(input: "_Tw", output: "_Tw"),
        .init(input: "_TWa", output: "_TWa"),
        .init(input: "_Twal", output: "_Twal"),
        .init(input: "_T", output: "_T"),
        .init(input: "_TTo", output: "_TTo"),
        .init(input: "_TC", output: "_TC"),
        .init(input: "_TM", output: "_TM"),
        .init(input: "_TW", output: "_TW"),
        .init(input: "_TWV", output: "_TWV"),
        .init(input: "_TWo", output: "_TWo"),
        .init(input: "_TWv", output: "_TWv"),
        .init(input: "_TWvd", output: "_TWvd"),
        .init(input: "_TWvi", output: "_TWvi"),
        .init(input: "_TWvx", output: "_TWvx"),
        .init(input: "_TtVCC4main3Foo4Ding3Str", output: "main.Foo.Ding.Str"),
        .init(input: "_TFVCC6nested6AClass12AnotherClass7AStruct9aFunctionfT1aSi_S2_", output: "nested.AClass.AnotherClass.AStruct.aFunction(a: Swift.Int) -> nested.AClass.AnotherClass.AStruct"),
        .init(input: "_TtXwC10attributes10SwiftClass", output: "weak attributes.SwiftClass"),
        .init(input: "_TtXoC10attributes10SwiftClass", output: "unowned attributes.SwiftClass"),
        .init(input: "_TtERR", output: "<ERROR TYPE>"),
        .init(input: "_TtGSqGSaC5sugar7MyClass__", output: "[sugar.MyClass]?"),
        .init(input: "_TtGSaGSqC5sugar7MyClass__", output: "[sugar.MyClass?]"),
        .init(input: "_TtaC9typealias5DWARF9DIEOffset", output: "typealias.DWARF.DIEOffset"),
        .init(input: "_Tta1t5Alias", output: "t.Alias"),
        .init(input: "_Ttas3Int", output: "Swift.Int"),
        .init(input: "_TTRXFo_dSc_dSb_XFo_iSc_iSb_", output: "reabstraction thunk helper from @callee_owned (@in Swift.UnicodeScalar) -> (@out Swift.Bool) to @callee_owned (@unowned Swift.UnicodeScalar) -> (@unowned Swift.Bool)"),
        .init(input: "_TTRXFo_dSi_dGSqSi__XFo_iSi_iGSqSi__", output: "reabstraction thunk helper from @callee_owned (@in Swift.Int) -> (@out Swift.Int?) to @callee_owned (@unowned Swift.Int) -> (@unowned Swift.Int?)"),
        .init(input: "_TTRGrXFo_iV18switch_abstraction1A_ix_XFo_dS0__ix_", output: "reabstraction thunk helper <A> from @callee_owned (@unowned switch_abstraction.A) -> (@out A) to @callee_owned (@in switch_abstraction.A) -> (@out A)"),
        .init(input: "_TFCF5types1gFT1bSb_T_L0_10Collection3zimfT_T_", output: "zim() -> () in Collection #2 in types.g(b: Swift.Bool) -> ()"),
        .init(input: "_TFF17capture_promotion22test_capture_promotionFT_FT_SiU_FT_Si_promote0", output: "closure #1 () -> Swift.Int in capture_promotion.test_capture_promotion() -> () -> Swift.Int with unmangled suffix \"_promote0\""),
        .init(input: "_TFIVs8_Processi10_argumentsGSaSS_U_FT_GSaSS_", output: "_arguments : [Swift.String] in variable initialization expression of Swift._Process with unmangled suffix \"U_FT_GSaSS_\""),
        .init(input: "_TFIvVs8_Process10_argumentsGSaSS_iU_FT_GSaSS_", output: "closure #1 () -> [Swift.String] in variable initialization expression of Swift._Process._arguments : [Swift.String]"),
        .init(input: "_TFCSo1AE", output: "__C.A.__ivar_destroyer"),
        .init(input: "_TFCSo1Ae", output: "__C.A.__ivar_initializer"),
        .init(input: "_TTWC13call_protocol1CS_1PS_FS1_3foofT_Si", output: "protocol witness for call_protocol.P.foo() -> Swift.Int in conformance call_protocol.C : call_protocol.P in call_protocol"),
        .init(input: "_T013call_protocol1CCAA1PA2aDP3fooSiyFTW", output: "protocol witness for call_protocol.P.foo() -> Swift.Int in conformance call_protocol.C : call_protocol.P in call_protocol"),
        .init(input: "_TFC12dynamic_self1X1ffT_DS0_", output: "dynamic_self.X.f() -> Self"),
        .init(input: "_TTSg5Si___TFSqcfT_GSqx_", output: "generic specialization <Swift.Int> of Swift.Optional.init() -> A?"),
        .init(input: "_TTSgq5Si___TFSqcfT_GSqx_", output: "generic specialization <serialized, Swift.Int> of Swift.Optional.init() -> A?"),
        .init(input: "_TTSg5SiSis3Foos_Sf___TFSqcfT_GSqx_", output: "generic specialization <Swift.Int with Swift.Int : Swift.Foo in Swift, Swift.Float> of Swift.Optional.init() -> A?"),
        .init(input: "_TTSg5Si_Sf___TFSqcfT_GSqx_", output: "generic specialization <Swift.Int, Swift.Float> of Swift.Optional.init() -> A?"),
        .init(input: "_TTSgS", output: "_TTSgS"),
        .init(input: "_TTSg5S", output: "_TTSg5S"),
        .init(input: "_TTSgSi", output: "_TTSgSi"),
        .init(input: "_TTSg5Si", output: "_TTSg5Si"),
        .init(input: "_TTSgSi_", output: "_TTSgSi_"),
        .init(input: "_TTSgSi__", output: "_TTSgSi__"),
        .init(input: "_TTSgSiS_", output: "_TTSgSiS_"),
        .init(input: "_TTSgSi__xyz", output: "_TTSgSi__xyz"),
        .init(input: "_TTSr5Si___TF4test7genericurFxx", output: "generic not re-abstracted specialization <Swift.Int> of test.generic<A>(A) -> A"),
        .init(input: "_TTSrq5Si___TF4test7genericurFxx", output: "generic not re-abstracted specialization <serialized, Swift.Int> of test.generic<A>(A) -> A"),
        .init(input: "_TPA__TTRXFo_oSSoSS_dSb_XFo_iSSiSS_dSb_", output: "partial apply forwarder for reabstraction thunk helper from @callee_owned (@in Swift.String, @in Swift.String) -> (@unowned Swift.Bool) to @callee_owned (@owned Swift.String, @owned Swift.String) -> (@unowned Swift.Bool)"),
        .init(input: "_TPAo__TTRGrXFo_dGSPx__dGSPx_zoPs5Error__XFo_iGSPx__iGSPx_zoPS___", output: "partial apply ObjC forwarder for reabstraction thunk helper <A> from @callee_owned (@in Swift.UnsafePointer<A>) -> (@out Swift.UnsafePointer<A>, @error @owned Swift.Error) to @callee_owned (@unowned Swift.UnsafePointer<A>) -> (@unowned Swift.UnsafePointer<A>, @error @owned Swift.Error)"),
        .init(input: "_T0S2SSbIxxxd_S2SSbIxiid_TRTA", output: "partial apply forwarder for reabstraction thunk helper from @callee_owned (@owned Swift.String, @owned Swift.String) -> (@unowned Swift.Bool) to @callee_owned (@in Swift.String, @in Swift.String) -> (@unowned Swift.Bool)"),
        .init(input: "_T0SPyxGAAs5Error_pIxydzo_A2AsAB_pIxirzo_lTRTa", output: "partial apply ObjC forwarder for reabstraction thunk helper <A> from @callee_owned (@unowned Swift.UnsafePointer<A>) -> (@unowned Swift.UnsafePointer<A>, @error @owned Swift.Error) to @callee_owned (@in Swift.UnsafePointer<A>) -> (@out Swift.UnsafePointer<A>, @error @owned Swift.Error)"),
        .init(input: "_TiC4Meow5MyCls9subscriptFT1iSi_Sf", output: "Meow.MyCls.subscript(i: Swift.Int) -> Swift.Float"),
        .init(input: "_TF8manglingX22egbpdajGbuEbxfgehfvwxnFT_T_", output: "mangling.ليهمابتكلموشعربي؟() -> ()"),
        .init(input: "_TF8manglingX24ihqwcrbEcvIaIdqgAFGpqjyeFT_T_", output: "mangling.他们为什么不说中文() -> ()"),
        .init(input: "_TF8manglingX27ihqwctvzcJBfGFJdrssDxIboAybFT_T_", output: "mangling.他們爲什麽不說中文() -> ()"),
        .init(input: "_TF8manglingX30Proprostnemluvesky_uybCEdmaEBaFT_T_", output: "mangling.Pročprostěnemluvíčesky() -> ()"),
        .init(input: "_TF8manglingXoi7p_qcaDcFTSiSi_Si", output: "mangling.«+» infix(Swift.Int, Swift.Int) -> Swift.Int"),
        .init(input: "_TF8manglingoi2qqFTSiSi_T_", output: "mangling.?? infix(Swift.Int, Swift.Int) -> ()"),
        .init(input: "_TFE11ext_structAV11def_structA1A4testfT_T_", output: "(extension in ext_structA):def_structA.A.test() -> ()"),
        .init(input: "_TF13devirt_accessP5_DISC15getPrivateClassFT_CS_P5_DISC12PrivateClass", output: "devirt_access.(getPrivateClass in _DISC)() -> devirt_access.(PrivateClass in _DISC)"),
        .init(input: "_TF4mainP5_mainX3wxaFT_T_", output: "main.(λ in _main)() -> ()"),
        .init(input: "_TF4mainP5_main3abcFT_aS_P5_DISC3xyz", output: "main.(abc in _main)() -> main.(xyz in _DISC)"),
        .init(input: "_TtPMP_", output: "Any.Type"),
        .init(input: "_TFCs13_NSSwiftArray29canStoreElementsOfDynamicTypefPMP_Sb", output: "Swift._NSSwiftArray.canStoreElementsOfDynamicType(Any.Type) -> Swift.Bool"),
        .init(input: "_TFCs13_NSSwiftArrayg17staticElementTypePMP_", output: "Swift._NSSwiftArray.staticElementType.getter : Any.Type"),
        .init(input: "_TFCs17_DictionaryMirrorg9valueTypePMP_", output: "Swift._DictionaryMirror.valueType.getter : Any.Type"),
        .init(input: "_TTSf1cl35_TFF7specgen6callerFSiT_U_FTSiSi_T_Si___TF7specgen12take_closureFFTSiSi_T_T_", output: "function signature specialization <Arg[0] = [Closure Propagated : closure #1 (Swift.Int, Swift.Int) -> () in specgen.caller(Swift.Int) -> (), Argument Types : [Swift.Int]> of specgen.take_closure((Swift.Int, Swift.Int) -> ()) -> ()"),
        .init(input: "_TTSfq1cl35_TFF7specgen6callerFSiT_U_FTSiSi_T_Si___TF7specgen12take_closureFFTSiSi_T_T_", output: "function signature specialization <serialized, Arg[0] = [Closure Propagated : closure #1 (Swift.Int, Swift.Int) -> () in specgen.caller(Swift.Int) -> (), Argument Types : [Swift.Int]> of specgen.take_closure((Swift.Int, Swift.Int) -> ()) -> ()"),
        .init(input: "_TTSf1cl35_TFF7specgen6callerFSiT_U_FTSiSi_T_Si___TTSg5Si___TF7specgen12take_closureFFTSiSi_T_T_", output: "function signature specialization <Arg[0] = [Closure Propagated : closure #1 (Swift.Int, Swift.Int) -> () in specgen.caller(Swift.Int) -> (), Argument Types : [Swift.Int]> of generic specialization <Swift.Int> of specgen.take_closure((Swift.Int, Swift.Int) -> ()) -> ()"),
        .init(input: "_TTSg5Si___TTSf1cl35_TFF7specgen6callerFSiT_U_FTSiSi_T_Si___TF7specgen12take_closureFFTSiSi_T_T_", output: "generic specialization <Swift.Int> of function signature specialization <Arg[0] = [Closure Propagated : closure #1 (Swift.Int, Swift.Int) -> () in specgen.caller(Swift.Int) -> (), Argument Types : [Swift.Int]> of specgen.take_closure((Swift.Int, Swift.Int) -> ()) -> ()"),
        .init(input: "_TTSf1cpfr24_TF8capturep6helperFSiT__n___TTRXFo_dSi_dT__XFo_iSi_dT__", output: "function signature specialization <Arg[0] = [Constant Propagated Function : capturep.helper(Swift.Int) -> ()]> of reabstraction thunk helper from @callee_owned (@in Swift.Int) -> (@unowned ()) to @callee_owned (@unowned Swift.Int) -> (@unowned ())"),
        .init(input: "_TTSf1cpfr24_TF8capturep6helperFSiT__n___TTRXFo_dSi_DT__XFo_iSi_DT__", output: "function signature specialization <Arg[0] = [Constant Propagated Function : capturep.helper(Swift.Int) -> ()]> of reabstraction thunk helper from @callee_owned (@in Swift.Int) -> (@unowned_inner_pointer ()) to @callee_owned (@unowned Swift.Int) -> (@unowned_inner_pointer ())"),
        .init(input: "_TTSf1cpi0_cpfl0_cpse0v4u123_cpg53globalinit_33_06E7F1D906492AE070936A9B58CBAE1C_token8_cpfr36_TFtest_capture_propagation2_closure___TF7specgen12take_closureFFTSiSi_T_T_", output: "function signature specialization <Arg[0] = [Constant Propagated Integer : 0], Arg[1] = [Constant Propagated Float : 0], Arg[2] = [Constant Propagated String : u8'u123'], Arg[3] = [Constant Propagated Global : globalinit_33_06E7F1D906492AE070936A9B58CBAE1C_token8], Arg[4] = [Constant Propagated Function : _TFtest_capture_propagation2_closure]> of specgen.take_closure((Swift.Int, Swift.Int) -> ()) -> ()"),
        .init(input: "_TTSf0gs___TFVs17_LegacyStringCore15_invariantCheckfT_T_", output: "function signature specialization <Arg[0] = Owned To Guaranteed and Exploded> of Swift._LegacyStringCore._invariantCheck() -> ()"),
        .init(input: "_TTSf2g___TTSf2s_d___TFVs17_LegacyStringCoreCfVs13_StringBufferS_", output: "function signature specialization <Arg[0] = Owned To Guaranteed> of function signature specialization <Arg[0] = Exploded, Arg[1] = Dead> of Swift._LegacyStringCore.init(Swift._StringBuffer) -> Swift._LegacyStringCore"),
        .init(input: "_TTSf2dg___TTSf2s_d___TFVs17_LegacyStringCoreCfVs13_StringBufferS_", output: "function signature specialization <Arg[0] = Dead and Owned To Guaranteed> of function signature specialization <Arg[0] = Exploded, Arg[1] = Dead> of Swift._LegacyStringCore.init(Swift._StringBuffer) -> Swift._LegacyStringCore"),
        .init(input: "_TTSf2dgs___TTSf2s_d___TFVs17_LegacyStringCoreCfVs13_StringBufferS_", output: "function signature specialization <Arg[0] = Dead and Owned To Guaranteed and Exploded> of function signature specialization <Arg[0] = Exploded, Arg[1] = Dead> of Swift._LegacyStringCore.init(Swift._StringBuffer) -> Swift._LegacyStringCore"),
        .init(input: "_TTSf3d_i_d_i_d_i___TFVs17_LegacyStringCoreCfVs13_StringBufferS_", output: "function signature specialization <Arg[0] = Dead, Arg[1] = Value Promoted from Box, Arg[2] = Dead, Arg[3] = Value Promoted from Box, Arg[4] = Dead, Arg[5] = Value Promoted from Box> of Swift._LegacyStringCore.init(Swift._StringBuffer) -> Swift._LegacyStringCore"),
        .init(input: "_TTSf3d_i_n_i_d_i___TFVs17_LegacyStringCoreCfVs13_StringBufferS_", output: "function signature specialization <Arg[0] = Dead, Arg[1] = Value Promoted from Box, Arg[3] = Value Promoted from Box, Arg[4] = Dead, Arg[5] = Value Promoted from Box> of Swift._LegacyStringCore.init(Swift._StringBuffer) -> Swift._LegacyStringCore"),
        .init(input: "_TFIZvV8mangling10HasVarInit5stateSbiu_KT_Sb", output: "implicit closure #1 : @autoclosure () -> Swift.Bool in variable initialization expression of static mangling.HasVarInit.state : Swift.Bool"),
        .init(input: "_TFFV23interface_type_mangling18GenericTypeContext23closureInGenericContexturFqd__T_L_3fooFTqd__x_T_", output: "foo #1 (A1, A) -> () in interface_type_mangling.GenericTypeContext.closureInGenericContext<A>(A1) -> ()"),
        .init(input: "_TFFV23interface_type_mangling18GenericTypeContextg31closureInGenericPropertyContextxL_3fooFT_x", output: "foo #1 () -> A in interface_type_mangling.GenericTypeContext.closureInGenericPropertyContext.getter : A"),
        .init(input: "_TTWurGV23interface_type_mangling18GenericTypeContextx_S_18GenericWitnessTestS_FS1_23closureInGenericContextuRxS1_rfqd__T_", output: "protocol witness for interface_type_mangling.GenericWitnessTest.closureInGenericContext<A where A: interface_type_mangling.GenericWitnessTest>(A1) -> () in conformance <A> interface_type_mangling.GenericTypeContext<A> : interface_type_mangling.GenericWitnessTest in interface_type_mangling"),
        .init(input: "_TTWurGV23interface_type_mangling18GenericTypeContextx_S_18GenericWitnessTestS_FS1_g31closureInGenericPropertyContextwx3Tee", output: "protocol witness for interface_type_mangling.GenericWitnessTest.closureInGenericPropertyContext.getter : A.Tee in conformance <A> interface_type_mangling.GenericTypeContext<A> : interface_type_mangling.GenericWitnessTest in interface_type_mangling"),
        .init(input: "_TTWurGV23interface_type_mangling18GenericTypeContextx_S_18GenericWitnessTestS_FS1_16twoParamsAtDepthu0_RxS1_rfTqd__1yqd_0__T_", output: "protocol witness for interface_type_mangling.GenericWitnessTest.twoParamsAtDepth<A, B where A: interface_type_mangling.GenericWitnessTest>(A1, y: B1) -> () in conformance <A> interface_type_mangling.GenericTypeContext<A> : interface_type_mangling.GenericWitnessTest in interface_type_mangling"),
        .init(input: "_TFC3red11BaseClassEHcfzT1aSi_S0_", output: "red.BaseClassEH.init(a: Swift.Int) throws -> red.BaseClassEH"),
        .init(input: "_TFe27mangling_generic_extensionsRxS_8RunciblerVS_3Foog1aSi", output: "(extension in mangling_generic_extensions):mangling_generic_extensions.Foo<A where A: mangling_generic_extensions.Runcible>.a.getter : Swift.Int"),
        .init(input: "_TFe27mangling_generic_extensionsRxS_8RunciblerVS_3Foog1bx", output: "(extension in mangling_generic_extensions):mangling_generic_extensions.Foo<A where A: mangling_generic_extensions.Runcible>.b.getter : A"),
        .init(input: "_TTRXFo_iT__iT_zoPs5Error__XFo__dT_zoPS___", output: "reabstraction thunk helper from @callee_owned () -> (@unowned (), @error @owned Swift.Error) to @callee_owned (@in ()) -> (@out (), @error @owned Swift.Error)"),
        .init(input: "_TFE1a", output: "_TFE1a"),
        .init(input: "_TF21$__lldb_module_for_E0au3$E0Ps5Error_", output: "$__lldb_module_for_E0.$E0.unsafeMutableAddressor : Swift.Error"),
        .init(input: "_TMps10Comparable", output: "protocol descriptor for Swift.Comparable"),
        .init(input: "_TFC4testP33_83378C430F65473055F1BD53F3ADCDB71C5doFoofT_T_", output: "test.(C in _83378C430F65473055F1BD53F3ADCDB7).doFoo() -> ()"),
        .init(input: "_TFVV15nested_generics5Lunch6DinnerCfT11firstCoursex12secondCourseGSqqd___9leftoversx14transformationFxqd___GS1_x_qd___", output: "nested_generics.Lunch.Dinner.init(firstCourse: A, secondCourse: A1?, leftovers: A, transformation: (A) -> A1) -> nested_generics.Lunch<A>.Dinner<A1>"),
        .init(input: "_TFVFC15nested_generics7HotDogs11applyRelishFT_T_L_6RelishCfT8materialx_GS1_x_", output: "init(material: A) -> Relish #1 in nested_generics.HotDogs.applyRelish() -> ()<A> in Relish #1 in nested_generics.HotDogs.applyRelish() -> ()"),
        .init(input: "_TFVFE15nested_genericsSS3fooFT_T_L_6CheeseCfT8materialx_GS0_x_", output: "init(material: A) -> Cheese #1 in (extension in nested_generics):Swift.String.foo() -> ()<A> in Cheese #1 in (extension in nested_generics):Swift.String.foo() -> ()"),
        .init(input: "_TTWOE5imojiCSo5Imoji14ImojiMatchRankS_9RankValueS_FS2_g9rankValueqq_Ss16RawRepresentable8RawValue", output: "_TTWOE5imojiCSo5Imoji14ImojiMatchRankS_9RankValueS_FS2_g9rankValueqq_Ss16RawRepresentable8RawValue"),
        .init(input: "_T0s17MutableCollectionP1asAARzs012RandomAccessB0RzsAA11SubSequences013BidirectionalB0PRpzsAdHRQlE06rotatecD05Indexs01_A9IndexablePQzAM15shiftingToStart_tFAJs01_J4BasePQzAQcfU_", output: "closure #1 (A.Swift._IndexableBase.Index) -> A.Swift._IndexableBase.Index in (extension in a):Swift.MutableCollection<A where A: Swift.MutableCollection, A: Swift.RandomAccessCollection, A.Swift.BidirectionalCollection.SubSequence: Swift.MutableCollection, A.Swift.BidirectionalCollection.SubSequence: Swift.RandomAccessCollection>.rotateRandomAccess(shiftingToStart: A.Swift._MutableIndexable.Index) -> A.Swift._MutableIndexable.Index"),
        .init(input: "_$Ss17MutableCollectionP1asAARzs012RandomAccessB0RzsAA11SubSequences013BidirectionalB0PRpzsAdHRQlE06rotatecD015shiftingToStart5Indexs01_A9IndexablePQzAN_tFAKs01_M4BasePQzAQcfU_", output: "closure #1 (A.Swift._IndexableBase.Index) -> A.Swift._IndexableBase.Index in (extension in a):Swift.MutableCollection<A where A: Swift.MutableCollection, A: Swift.RandomAccessCollection, A.Swift.BidirectionalCollection.SubSequence: Swift.MutableCollection, A.Swift.BidirectionalCollection.SubSequence: Swift.RandomAccessCollection>.rotateRandomAccess(shiftingToStart: A.Swift._MutableIndexable.Index) -> A.Swift._MutableIndexable.Index"),
        .init(input: "_T03foo4_123ABTf3psbpsb_n", output: "function signature specialization <Arg[0] = [Constant Propagated String : u8'123'], Arg[1] = [Constant Propagated String : u8'123']> of foo"),
        .init(input: "_T04main5innerys5Int32Vz_yADctF25closure_with_box_argumentxz_Bi32__lXXTf1nc_n", output: "function signature specialization <Arg[1] = [Closure Propagated : closure_with_box_argument, Argument Types : [<A> { var A } <Builtin.Int32>]> of main.inner(inout Swift.Int32, (Swift.Int32) -> ()) -> ()"),
        .init(input: "_$S4main5inneryys5Int32Vz_yADctF25closure_with_box_argumentxz_Bi32__lXXTf1nc_n", output: "function signature specialization <Arg[1] = [Closure Propagated : closure_with_box_argument, Argument Types : [<A> { var A } <Builtin.Int32>]> of main.inner(inout Swift.Int32, (Swift.Int32) -> ()) -> ()"),
        .init(input: "_T03foo6testityyyc_yyctF1a1bTf3pfpf_n", output: "function signature specialization <Arg[0] = [Constant Propagated Function : a], Arg[1] = [Constant Propagated Function : b]> of foo.testit(() -> (), () -> ()) -> ()"),
        .init(input: "_$S3foo6testityyyyc_yyctF1a1bTf3pfpf_n", output: "function signature specialization <Arg[0] = [Constant Propagated Function : a], Arg[1] = [Constant Propagated Function : b]> of foo.testit(() -> (), () -> ()) -> ()"),
        .init(input: "_SocketJoinOrLeaveMulticast", output: "_SocketJoinOrLeaveMulticast"),
        .init(input: "_T0s10DictionaryV3t17E6Index2V1loiSbAEyxq__G_AGtFZ", output: "static (extension in t17):Swift.Dictionary.Index2.< infix((extension in t17):[A : B].Index2, (extension in t17):[A : B].Index2) -> Swift.Bool"),
        .init(input: "_T08mangling14varargsVsArrayySi3arrd_SS1ntF", output: "mangling.varargsVsArray(arr: Swift.Int..., n: Swift.String) -> ()"),
        .init(input: "_T08mangling14varargsVsArrayySaySiG3arr_SS1ntF", output: "mangling.varargsVsArray(arr: [Swift.Int], n: Swift.String) -> ()"),
        .init(input: "_T08mangling14varargsVsArrayySaySiG3arrd_SS1ntF", output: "mangling.varargsVsArray(arr: [Swift.Int]..., n: Swift.String) -> ()"),
        .init(input: "_T08mangling14varargsVsArrayySi3arrd_tF", output: "mangling.varargsVsArray(arr: Swift.Int...) -> ()"),
        .init(input: "_T08mangling14varargsVsArrayySaySiG3arrd_tF", output: "mangling.varargsVsArray(arr: [Swift.Int]...) -> ()"),
        .init(input: "_$Ss10DictionaryV3t17E6Index2V1loiySbAEyxq__G_AGtFZ", output: "static (extension in t17):Swift.Dictionary.Index2.< infix((extension in t17):[A : B].Index2, (extension in t17):[A : B].Index2) -> Swift.Bool"),
        .init(input: "_$S8mangling14varargsVsArray3arr1nySid_SStF", output: "mangling.varargsVsArray(arr: Swift.Int..., n: Swift.String) -> ()"),
        .init(input: "_$S8mangling14varargsVsArray3arr1nySaySiG_SStF", output: "mangling.varargsVsArray(arr: [Swift.Int], n: Swift.String) -> ()"),
        .init(input: "_$S8mangling14varargsVsArray3arr1nySaySiGd_SStF", output: "mangling.varargsVsArray(arr: [Swift.Int]..., n: Swift.String) -> ()"),
        .init(input: "_$S8mangling14varargsVsArray3arrySid_tF", output: "mangling.varargsVsArray(arr: Swift.Int...) -> ()"),
        .init(input: "_$S8mangling14varargsVsArray3arrySaySiGd_tF", output: "mangling.varargsVsArray(arr: [Swift.Int]...) -> ()"),
        .init(input: "_T0s13_UnicodeViewsVss22RandomAccessCollectionRzs0A8EncodingR_11SubSequence_5IndexQZAFRtzsAcERpzAE_AEQZAIRSs15UnsignedInteger8Iterator_7ElementRPzAE_AlMQZANRS13EncodedScalar_AlMQY_AORSr0_lE13CharacterViewVyxq__G", output: "(extension in Swift):Swift._UnicodeViews<A, B><A, B where A: Swift.RandomAccessCollection, B: Swift.UnicodeEncoding, A.Index == A.SubSequence.Index, A.SubSequence: Swift.RandomAccessCollection, A.SubSequence == A.SubSequence.SubSequence, A.Iterator.Element: Swift.UnsignedInteger, A.Iterator.Element == A.SubSequence.Iterator.Element, A.SubSequence.Iterator.Element == B.EncodedScalar.Iterator.Element>.CharacterView"),
        .init(input: "_T010Foundation11MeasurementV12SimulatorKitSo9UnitAngleCRszlE11OrientationO2eeoiSbAcDEAGOyAF_G_AKtFZ", output: "static (extension in SimulatorKit):Foundation.Measurement<A where A == __C.UnitAngle>.Orientation.== infix((extension in SimulatorKit):Foundation.Measurement<__C.UnitAngle>.Orientation, (extension in SimulatorKit):Foundation.Measurement<__C.UnitAngle>.Orientation) -> Swift.Bool"),
        .init(input: "_$S10Foundation11MeasurementV12SimulatorKitSo9UnitAngleCRszlE11OrientationO2eeoiySbAcDEAGOyAF_G_AKtFZ", output: "static (extension in SimulatorKit):Foundation.Measurement<A where A == __C.UnitAngle>.Orientation.== infix((extension in SimulatorKit):Foundation.Measurement<__C.UnitAngle>.Orientation, (extension in SimulatorKit):Foundation.Measurement<__C.UnitAngle>.Orientation) -> Swift.Bool"),
        .init(input: "_T04main1_yyF", output: "main._() -> ()"),
        .init(input: "_T04test6testitSiyt_tF", output: "test.testit(()) -> Swift.Int"),
        .init(input: "_$S4test6testitySiyt_tF", output: "test.testit(()) -> Swift.Int"),
        .init(input: "_T08_ElementQzSbs5Error_pIxxdzo_ABSbsAC_pIxidzo_s26RangeReplaceableCollectionRzABRLClTR", output: "reabstraction thunk helper <A where A: Swift.RangeReplaceableCollection, A._Element: AnyObject> from @callee_owned (@owned A._Element) -> (@unowned Swift.Bool, @error @owned Swift.Error) to @callee_owned (@in A._Element) -> (@unowned Swift.Bool, @error @owned Swift.Error)"),
        .init(input: "_T0Ix_IyB_Tr", output: "reabstraction thunk from @callee_owned () -> () to @callee_unowned @convention(block) () -> ()"),
        .init(input: "_T0Rml", output: "_T0Rml"),
        .init(input: "_T0Tk", output: "_T0Tk"),
        .init(input: "_T0A8", output: "_T0A8"),
        .init(input: "_T0s30ReversedRandomAccessCollectionVyxGTfq3nnpf_nTfq1cn_nTfq4x_n", output: "_T0s30ReversedRandomAccessCollectionVyxGTfq3nnpf_nTfq1cn_nTfq4x_n"),
        .init(input: "_T03abc6testitySiFTm", output: "merged abc.testit(Swift.Int) -> ()"),
        .init(input: "_T04main4TestCACSi1x_tc6_PRIV_Llfc", output: "main.Test.(in _PRIV_).init(x: Swift.Int) -> main.Test"),
        .init(input: "_$S3abc6testityySiFTm", output: "merged abc.testit(Swift.Int) -> ()"),
        .init(input: "_$S4main4TestC1xACSi_tc6_PRIV_Llfc", output: "main.Test.(in _PRIV_).init(x: Swift.Int) -> main.Test"),
        .init(input: "_T0SqWOy.17", output: "outlined copy of Swift.Optional with unmangled suffix \".17\""),
        .init(input: "_T0SqWOC", output: "outlined init with copy of Swift.Optional"),
        .init(input: "_T0SqWOD", output: "outlined assign with take of Swift.Optional"),
        .init(input: "_T0SqWOF", output: "outlined assign with copy of Swift.Optional"),
        .init(input: "_T0SqWOH", output: "outlined destroy of Swift.Optional"),
        .init(input: "_T03nix6testitSaySiGyFTv_", output: "outlined variable #0 of nix.testit() -> [Swift.Int]"),
        .init(input: "_T03nix6testitSaySiGyFTv_r", output: "outlined read-only object #0 of nix.testit() -> [Swift.Int]"),
        .init(input: "_T03nix6testitSaySiGyFTv0_", output: "outlined variable #1 of nix.testit() -> [Swift.Int]"),
        .init(input: "_T0So11UITextFieldC4textSSSgvgToTepb_", output: "outlined bridged method (pb) of @objc __C.UITextField.text.getter : Swift.String?"),
        .init(input: "_T0So11UITextFieldC4textSSSgvgToTeab_", output: "outlined bridged method (ab) of @objc __C.UITextField.text.getter : Swift.String?"),
        .init(input: "$sSo5GizmoC11doSomethingyypSgSaySSGSgFToTembgnn_", output: "outlined bridged method (mbgnn) of @objc __C.Gizmo.doSomething([Swift.String]?) -> Any?"),
        .init(input: "_T04test1SVyxGAA1RA2A1ZRzAA1Y2ZZRpzl1A_AhaGPWT", output: "associated type witness table accessor for A.ZZ : test.Y in <A where A: test.Z, A.ZZ: test.Y> test.S<A> : test.R in test"),
        .init(input: "_T0s24_UnicodeScalarExceptions33_0E4228093681F6920F0AB2E48B4F1C69LLVACycfC", output: "Swift.(_UnicodeScalarExceptions in _0E4228093681F6920F0AB2E48B4F1C69).init() -> Swift.(_UnicodeScalarExceptions in _0E4228093681F6920F0AB2E48B4F1C69)"),
        .init(input: "_T0D", output: "_T0D"),
        .init(input: "_T0s18EnumeratedIteratorVyxGs8Sequencess0B8ProtocolRzlsADP5splitSay03SubC0QzGSi9maxSplits_Sb25omittingEmptySubsequencesSb7ElementQzKc14whereSeparatortKFTW", output: "protocol witness for Swift.Sequence.split(maxSplits: Swift.Int, omittingEmptySubsequences: Swift.Bool, whereSeparator: (A.Element) throws -> Swift.Bool) throws -> [A.SubSequence] in conformance <A where A: Swift.IteratorProtocol> Swift.EnumeratedIterator<A> : Swift.Sequence in Swift"),
        .init(input: "_T0s3SetVyxGs10CollectiotySivm", output: "_T0s3SetVyxGs10CollectiotySivm"),
        .init(input: "_S$s3SetVyxGs10CollectiotySivm", output: "_S$s3SetVyxGs10CollectiotySivm"),
        .init(input: "_T0s18ReversedCollectionVyxGs04LazyB8ProtocolfC", output: "_T0s18ReversedCollectionVyxGs04LazyB8ProtocolfC"),
        .init(input: "_S$s18ReversedCollectionVyxGs04LazyB8ProtocolfC", output: "_S$s18ReversedCollectionVyxGs04LazyB8ProtocolfC"),
        .init(input: "_T0iW", output: "_T0iW"),
        .init(input: "_S$iW", output: "_S$iW"),
        .init(input: "_T0s5print_9separator10terminatoryypfC", output: "_T0s5print_9separator10terminatoryypfC"),
        .init(input: "_S$s5print_9separator10terminatoryypfC", output: "_S$s5print_9separator10terminatoryypfC"),
        .init(input: "_T0So13GenericOptionas8HashableSCsACP9hashValueSivgTW", output: "protocol witness for Swift.Hashable.hashValue.getter : Swift.Int in conformance __C.GenericOption : Swift.Hashable in __C_Synthesized"),
        .init(input: "_T0So11CrappyColorVs16RawRepresentableSCMA", output: "reflection metadata associated type descriptor __C.CrappyColor : Swift.RawRepresentable in __C_Synthesized"),
        .init(input: "$S28protocol_conformance_records15NativeValueTypeVAA8RuncibleAAMc", output: "protocol conformance descriptor for protocol_conformance_records.NativeValueType : protocol_conformance_records.Runcible in protocol_conformance_records"),
        .init(input: "$ss6SimpleHr", output: "protocol descriptor runtime record for Swift.Simple"),
        .init(input: "$ss5OtherVs6SimplesHc", output: "protocol conformance descriptor runtime record for Swift.Other : Swift.Simple in Swift"),
        .init(input: "$ss5OtherVHn", output: "nominal type descriptor runtime record for Swift.Other"),
        .init(input: "$s18opaque_return_type3fooQryFQOHo", output: "opaque type descriptor runtime record for <<opaque return type of opaque_return_type.foo() -> some>>"),
        .init(input: "$SSC9SomeErrorLeVD", output: "__C_Synthesized.related decl 'e' for SomeError"),
        .init(input: "$s20mangling_retroactive5test0yyAA1ZVy12RetroactiveB1XVSiAE1YVAG0D1A1PAAyHCg_AiJ1QAAyHCg1_GF", output: "mangling_retroactive.test0(mangling_retroactive.Z<RetroactiveB.X, Swift.Int, RetroactiveB.Y>) -> ()"),
        .init(input: "$s20mangling_retroactive5test0yyAA1ZVy12RetroactiveB1XVSiAE1YVAG0D1A1PHPyHCg_AiJ1QHPyHCg1_GF", output: "mangling_retroactive.test0(mangling_retroactive.Z<RetroactiveB.X, Swift.Int, RetroactiveB.Y>) -> ()"),
        .init(input: "$s20mangling_retroactive5test0yyAA1ZVy12RetroactiveB1XVSiAE1YVAG0D1A1PHpyHCg_AiJ1QHpyHCg1_GF", output: "mangling_retroactive.test0(mangling_retroactive.Z<RetroactiveB.X, Swift.Int, RetroactiveB.Y>) -> ()"),
        .init(input: "_T0LiteralAByxGxd_tcfC", output: "_T0LiteralAByxGxd_tcfC"),
        .init(input: "_T0XZ", output: "_T0XZ"),
        .init(input: "_TTSf0os___TFVs17_LegacyStringCore15_invariantCheckfT_T_", output: "function signature specialization <Arg[0] = Guaranteed To Owned and Exploded> of Swift._LegacyStringCore._invariantCheck() -> ()"),
        .init(input: "_TTSf2o___TTSf2s_d___TFVs17_LegacyStringCoreCfVs13_StringBufferS_", output: "function signature specialization <Arg[0] = Guaranteed To Owned> of function signature specialization <Arg[0] = Exploded, Arg[1] = Dead> of Swift._LegacyStringCore.init(Swift._StringBuffer) -> Swift._LegacyStringCore"),
        .init(input: "_TTSf2do___TTSf2s_d___TFVs17_LegacyStringCoreCfVs13_StringBufferS_", output: "function signature specialization <Arg[0] = Dead and Guaranteed To Owned> of function signature specialization <Arg[0] = Exploded, Arg[1] = Dead> of Swift._LegacyStringCore.init(Swift._StringBuffer) -> Swift._LegacyStringCore"),
        .init(input: "_TTSf2dos___TTSf2s_d___TFVs17_LegacyStringCoreCfVs13_StringBufferS_", output: "function signature specialization <Arg[0] = Dead and Guaranteed To Owned and Exploded> of function signature specialization <Arg[0] = Exploded, Arg[1] = Dead> of Swift._LegacyStringCore.init(Swift._StringBuffer) -> Swift._LegacyStringCore"),
        .init(input: "_TTSf", output: "_TTSf"),
        .init(input: "_TtW0_j", output: "_TtW0_j"),
        .init(input: "_TtW_4m3a3v", output: "_TtW_4m3a3v"),
        .init(input: "_TVGVGSS_2v0", output: "_TVGVGSS_2v0"),
        .init(input: "$SSD1BySSSBsg_G", output: "$SSD1BySSSBsg_G"),
        .init(input: "_Ttu4222222222222222222222222_rW_2T_2TJ_", output: "<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AB, BB, CB, DB, EB, FB, GB, HB, IB, JB, KB, LB, MB, NB, OB, PB, QB, RB, SB, TB, UB, VB, WB, XB, YB, ZB, AC, BC, CC, DC, EC, FC, GC, HC, IC, JC, KC, LC, MC, NC, OC, PC, QC, RC, SC, TC, UC, VC, WC, XC, YC, ZC, AD, BD, CD, DD, ED, FD, GD, HD, ID, JD, KD, LD, MD, ND, OD, PD, QD, RD, SD, TD, UD, VD, WD, XD, YD, ZD, AE, BE, CE, DE, EE, FE, GE, HE, IE, JE, KE, LE, ME, NE, OE, PE, QE, RE, SE, TE, UE, VE, WE, XE, ...> B.T_.TJ"),
        .init(input: "_$S3BBBBf0602365061_", output: "_$S3BBBBf0602365061_"),
        .init(input: "_$S3BBBBi0602365061_", output: "_$S3BBBBi0602365061_"),
        .init(input: "_$S3BBBBv0602365061_", output: "_$S3BBBBv0602365061_"),
        .init(input: "_T0lxxxmmmTk", output: "_T0lxxxmmmTk"),
        .init(input: "_TtCF4test11doNotCrash1FT_QuL_8MyClass1", output: "MyClass1 #1 in test.doNotCrash1() -> some"),
        .init(input: "$s3Bar3FooVAA5DrinkVyxGs5Error_pSeRzSERzlyShy4AbcdAHO6MemberVGALSeHPAKSeAAyHC_HCg_ALSEHPAKSEAAyHC_HCg0_Iseggozo_SgWOe", output: "outlined consume of (@escaping @callee_guaranteed @substituted <A where A: Swift.Decodable, A: Swift.Encodable> (@guaranteed Bar.Foo) -> (@owned Bar.Drink<A>, @error @owned Swift.Error) for <Swift.Set<Abcd.Abcd.Member>>)?"),
        .init(input: "$s4Test5ProtoP8IteratorV10collectionAEy_qd__Gqd___tcfc", output: "Test.Proto.Iterator.init(collection: A1) -> Test.Proto.Iterator<A1>"),
        .init(input: "$s4test3fooV4blahyAA1SV1fQryFQOy_Qo_AHF", output: "test.foo.blah(<<opaque return type of test.S.f() -> some>>.0) -> <<opaque return type of test.S.f() -> some>>.0"),
        .init(input: "$S3nix8MystructV1xACyxGx_tcfc7MyaliasL_ayx__GD", output: "Myalias #1 in nix.Mystruct<A>.init(x: A) -> nix.Mystruct<A>"),
        .init(input: "$S3nix7MyclassCfd7MyaliasL_ayx__GD", output: "Myalias #1 in nix.Myclass<A>.deinit"),
        .init(input: "$S3nix8MystructVyS2icig7MyaliasL_ayx__GD", output: "Myalias #1 in nix.Mystruct<A>.subscript.getter : (Swift.Int) -> Swift.Int"),
        .init(input: "$S3nix8MystructV1x1uACyxGx_qd__tclufc7MyaliasL_ayx_qd___GD", output: "Myalias #1 in nix.Mystruct<A>.<A1>(x: A, u: A1) -> nix.Mystruct<A>"),
        .init(input: "$S3nix8MystructV6testit1xyx_tF7MyaliasL_ayx__GD", output: "Myalias #1 in nix.Mystruct<A>.testit(x: A) -> ()"),
        .init(input: "$S3nix8MystructV6testit1x1u1vyx_qd__qd_0_tr0_lF7MyaliasL_ayx_qd__qd_0__GD", output: "Myalias #1 in nix.Mystruct<A>.testit<A1, B1>(x: A, u: A1, v: B1) -> ()"),
        .init(input: "$S4blah8PatatinoaySiGD", output: "blah.Patatino<Swift.Int>"),
        .init(input: "$SSiSHsWP", output: "protocol witness table for Swift.Int : Swift.Hashable in Swift"),
        .init(input: "$S7TestMod5OuterV3Fooayx_SiGD", output: "TestMod.Outer<A>.Foo<Swift.Int>"),
        .init(input: "$Ss17_VariantSetBufferO05CocoaC0ayx_GD", output: "Swift._VariantSetBuffer<A>.CocoaBuffer"),
        .init(input: "$S2t21QP22ProtocolTypeAliasThingayAA4BlahV5SomeQa_GSgD", output: "t2.Blah.SomeQ as t2.Q.ProtocolTypeAliasThing?"),
        .init(input: "$s1A1gyyxlFx_qd__t_Ti5", output: "inlined generic function <(A, A1)> of A.g<A>(A) -> ()"),
        .init(input: "$S1T19protocol_resilience17ResilientProtocolPTl", output: "associated type descriptor for protocol_resilience.ResilientProtocol.T"),
        .init(input: "$S18resilient_protocol21ResilientBaseProtocolTL", output: "protocol requirements base descriptor for resilient_protocol.ResilientBaseProtocol"),
        .init(input: "$S1t1PP10AssocType2_AA1QTn", output: "associated conformance descriptor for t.P.AssocType2: t.Q"),
        .init(input: "$S1t1PP10AssocType2_AA1QTN", output: "default associated conformance accessor for t.P.AssocType2: t.Q"),
        .init(input: "$s4Test6testityyxlFAA8MystructV_TB5", output: "generic specialization <Test.Mystruct> of Test.testit<A>(A) -> ()"),
        .init(input: "$sSUss17FixedWidthIntegerRzrlEyxqd__cSzRd__lufCSu_SiTg5", output: "generic specialization <Swift.UInt, Swift.Int> of (extension in Swift):Swift.UnsignedInteger< where A: Swift.FixedWidthInteger>.init<A where A1: Swift.BinaryInteger>(A1) -> A"),
        .init(input: "$s4test7genFuncyyx_q_tr0_lFSi_SbTtt1g5", output: "generic specialization <Swift.Int, Swift.Bool> of test.genFunc<A, B>(A, B) -> ()"),
        .init(input: "$sSD5IndexVy__GD", output: "$sSD5IndexVy__GD"),
        .init(input: "$s4test3StrCACycfC", output: "test.Str.__allocating_init() -> test.Str"),
        .init(input: "$s18keypaths_inlinable13KeypathStructV8computedSSvpACTKq", output: "key path getter for keypaths_inlinable.KeypathStruct.computed : Swift.String : keypaths_inlinable.KeypathStruct, serialized"),
        .init(input: "$s3red4testyAA3ResOyxSayq_GAEs5ErrorAAq_sAFHD1__HCg_GADyxq_GsAFR_r0_lF", output: "red.test<A, B where B: Swift.Error>(red.Res<A, B>) -> red.Res<A, [B]>"),
        .init(input: "$s3red4testyAA7OurTypeOy4them05TheirD0Vy5AssocQzGAjE0F8ProtocolAAxAA0c7DerivedH0HD1_AA0c4BaseH0HI1_AieKHA2__HCg_GxmAaLRzlF", output: "red.test<A where A: red.OurDerivedProtocol>(A.Type) -> red.OurType<them.TheirType<A.Assoc>>"),
        .init(input: "$s17property_wrappers10WithTuplesV9fractionsSd_S2dtvpfP", output: "property wrapper backing initializer of property_wrappers.WithTuples.fractions : (Swift.Double, Swift.Double, Swift.Double)"),
        .init(input: "$sSo17OS_dispatch_queueC4sync7executeyyyXE_tFTOTA", output: "partial apply forwarder for @nonobjc __C.OS_dispatch_queue.sync(execute: () -> ()) -> ()"),
        .init(input: "$s4main1gyySiXCvp", output: "main.g : @convention(c) (Swift.Int) -> ()"),
        .init(input: "$s4main1gyySiXBvp", output: "main.g : @convention(block) (Swift.Int) -> ()"),
        .init(input: "$sxq_Ifgnr_D", output: "@differentiable(_forward) @callee_guaranteed (@in_guaranteed A) -> (@out B)"),
        .init(input: "$sxq_Irgnr_D", output: "@differentiable(reverse) @callee_guaranteed (@in_guaranteed A) -> (@out B)"),
        .init(input: "$sxq_Idgnr_D", output: "@differentiable @callee_guaranteed (@in_guaranteed A) -> (@out B)"),
        .init(input: "$sxq_Ilgnr_D", output: "@differentiable(_linear) @callee_guaranteed (@in_guaranteed A) -> (@out B)"),
        .init(input: "$sS3fIedgyywd_D", output: "@escaping @differentiable @callee_guaranteed (@unowned Swift.Float, @unowned @noDerivative Swift.Float) -> (@unowned Swift.Float)"),
        .init(input: "$sS5fIertyyywddw_D", output: "@escaping @differentiable(reverse) @convention(thin) (@unowned Swift.Float, @unowned Swift.Float, @unowned @noDerivative Swift.Float) -> (@unowned Swift.Float, @unowned @noDerivative Swift.Float)"),
        .init(input: "$syQo", output: "$syQo"),
        .init(input: "$s0059xxxxxxxxxxxxxxx_ttttttttBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBee", output: "$s0059xxxxxxxxxxxxxxx_ttttttttBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBee"),
        .init(input: "$sx1td_t", output: "(t: A...)"),
        .init(input: "$s7example1fyyYaF", output: "example.f() async -> ()"),
        .init(input: "$s7example1fyyYaKF", output: "example.f() async throws -> ()"),
        .init(input: "$s4main20receiveInstantiationyySo34__CxxTemplateInst12MagicWrapperIiEVzF", output: "main.receiveInstantiation(inout __C.__CxxTemplateInst12MagicWrapperIiE) -> ()"),
        .init(input: "$s4main19returnInstantiationSo34__CxxTemplateInst12MagicWrapperIiEVyF", output: "main.returnInstantiation() -> __C.__CxxTemplateInst12MagicWrapperIiE"),
        .init(input: "$s4main6testityyYaFTu", output: "async function pointer to main.testit() async -> ()"),
        .init(input: "$s13test_mangling3fooyS2f_S2ftFTJfUSSpSr", output: "forward-mode derivative of test_mangling.foo(Swift.Float, Swift.Float, Swift.Float) -> Swift.Float with respect to parameters {1, 2} and results {0}"),
        .init(input: "$s13test_mangling4foo21xq_x_t16_Differentiation14DifferentiableR_AA1P13TangentVectorRp_r0_lFAdERzAdER_AafGRpzAafHRQr0_lTJrSpSr", output: "reverse-mode derivative of test_mangling.foo2<A, B where B: _Differentiation.Differentiable, B.TangentVector: test_mangling.P>(x: A) -> B with respect to parameters {0} and results {0} with <A, B where A: _Differentiation.Differentiable, B: _Differentiation.Differentiable, A.TangentVector: test_mangling.P, B.TangentVector: test_mangling.P>"),
        .init(input: "$s13test_mangling4foo21xq_x_t16_Differentiation14DifferentiableR_AA1P13TangentVectorRp_r0_lFAdERzAdER_AafGRpzAafHRQr0_lTJVrSpSr", output: "vtable thunk for reverse-mode derivative of test_mangling.foo2<A, B where B: _Differentiation.Differentiable, B.TangentVector: test_mangling.P>(x: A) -> B with respect to parameters {0} and results {0} with <A, B where A: _Differentiation.Differentiable, B: _Differentiation.Differentiable, A.TangentVector: test_mangling.P, B.TangentVector: test_mangling.P>"),
        .init(input: "$s13test_mangling3fooyS2f_xq_t16_Differentiation14DifferentiableR_r0_lFAcDRzAcDR_r0_lTJpUSSpSr", output: "pullback of test_mangling.foo<A, B where B: _Differentiation.Differentiable>(Swift.Float, A, B) -> Swift.Float with respect to parameters {1, 2} and results {0} with <A, B where A: _Differentiation.Differentiable, B: _Differentiation.Differentiable>"),
        .init(input: "$s13test_mangling4foo21xq_x_t16_Differentiation14DifferentiableR_AA1P13TangentVectorRp_r0_lFTSAdERzAdER_AafGRpzAafHRQr0_lTJrSpSr", output: "reverse-mode derivative of protocol self-conformance witness for test_mangling.foo2<A, B where B: _Differentiation.Differentiable, B.TangentVector: test_mangling.P>(x: A) -> B with respect to parameters {0} and results {0} with <A, B where A: _Differentiation.Differentiable, B: _Differentiation.Differentiable, A.TangentVector: test_mangling.P, B.TangentVector: test_mangling.P>"),
        .init(input: "$s13test_mangling3fooyS2f_xq_t16_Differentiation14DifferentiableR_r0_lFAcDRzAcDR_r0_lTJpUSSpSrTj", output: "dispatch thunk of pullback of test_mangling.foo<A, B where B: _Differentiation.Differentiable>(Swift.Float, A, B) -> Swift.Float with respect to parameters {1, 2} and results {0} with <A, B where A: _Differentiation.Differentiable, B: _Differentiation.Differentiable>"),
        .init(input: "$s13test_mangling3fooyS2f_xq_t16_Differentiation14DifferentiableR_r0_lFAcDRzAcDR_r0_lTJpUSSpSrTq", output: "method descriptor for pullback of test_mangling.foo<A, B where B: _Differentiation.Differentiable>(Swift.Float, A, B) -> Swift.Float with respect to parameters {1, 2} and results {0} with <A, B where A: _Differentiation.Differentiable, B: _Differentiation.Differentiable>"),
        .init(input: "$s13TangentVector16_Differentiation14DifferentiablePQzAaDQy_SdAFIegnnnr_TJSdSSSpSrSUSP", output: "autodiff subset parameters thunk for differential from @escaping @callee_guaranteed (@in_guaranteed A._Differentiation.Differentiable.TangentVector, @in_guaranteed B._Differentiation.Differentiable.TangentVector, @in_guaranteed Swift.Double) -> (@out B._Differentiation.Differentiable.TangentVector) with respect to parameters {0, 1, 2} and results {0} to parameters {0, 2}"),
        .init(input: "$s13TangentVector16_Differentiation14DifferentiablePQy_AaDQzAESdIegnrrr_TJSpSSSpSrSUSP", output: "autodiff subset parameters thunk for pullback from @escaping @callee_guaranteed (@in_guaranteed B._Differentiation.Differentiable.TangentVector) -> (@out A._Differentiation.Differentiable.TangentVector, @out B._Differentiation.Differentiable.TangentVector, @out Swift.Double) with respect to parameters {0, 1, 2} and results {0} to parameters {0, 2}"),
        .init(input: "$s39differentiation_subset_parameters_thunk19inoutIndirectCalleryq_x_q_q0_t16_Differentiation14DifferentiableRzAcDR_AcDR0_r1_lFxq_Sdq_xq_Sdr0_ly13TangentVectorAcDPQy_AeFQzIsegnrr_Iegnnnro_TJSrSSSpSrSUSP", output: "autodiff subset parameters thunk for reverse-mode derivative from differentiation_subset_parameters_thunk.inoutIndirectCaller<A, B, C where A: _Differentiation.Differentiable, B: _Differentiation.Differentiable, C: _Differentiation.Differentiable>(A, B, C) -> B with respect to parameters {0, 1, 2} and results {0} to parameters {0, 2} of type @escaping @callee_guaranteed (@in_guaranteed A, @in_guaranteed B, @in_guaranteed Swift.Double) -> (@out B, @owned @escaping @callee_guaranteed @substituted <A, B> (@in_guaranteed A) -> (@out B, @out Swift.Double) for <B._Differentiation.Differentiable.TangentVectorA._Differentiation.Differentiable.TangentVector>)"),
        .init(input: "$sS2f8mangling3FooV13TangentVectorVIegydd_SfAESfIegydd_TJOp", output: "autodiff self-reordering reabstraction thunk for pullback from @escaping @callee_guaranteed (@unowned Swift.Float) -> (@unowned Swift.Float, @unowned mangling.Foo.TangentVector) to @escaping @callee_guaranteed (@unowned Swift.Float) -> (@unowned mangling.Foo.TangentVector, @unowned Swift.Float)"),
        .init(input: "$s13test_mangling3fooyS2f_S2ftFWJrSpSr", output: "reverse-mode differentiability witness for test_mangling.foo(Swift.Float, Swift.Float, Swift.Float) -> Swift.Float with respect to parameters {0} and results {0}"),
        .init(input: "$s13test_mangling3fooyS2f_xq_t16_Differentiation14DifferentiableR_r0_lFAcDRzAcDR_r0_lWJrUSSpSr", output: "reverse-mode differentiability witness for test_mangling.foo<A, B where B: _Differentiation.Differentiable>(Swift.Float, A, B) -> Swift.Float with respect to parameters {1, 2} and results {0} with <A, B where A: _Differentiation.Differentiable, B: _Differentiation.Differentiable>"),
        .init(input: "$s5async1hyyS2iYbXEF", output: "async.h(@Sendable (Swift.Int) -> Swift.Int) -> ()"),
        .init(input: "$s5Actor02MyA0C17testAsyncFunctionyyYaKFTY0_", output: "(1) suspend resume partial function for Actor.MyActor.testAsyncFunction() async throws -> ()"),
        .init(input: "$s5Actor02MyA0C17testAsyncFunctionyyYaKFTQ1_", output: "(2) await resume partial function for Actor.MyActor.testAsyncFunction() async throws -> ()"),
        .init(input: "$s4diff1hyyS2iYjfXEF", output: "diff.h(@differentiable(_forward) (Swift.Int) -> Swift.Int) -> ()"),
        .init(input: "$s4diff1hyyS2iYjrXEF", output: "diff.h(@differentiable(reverse) (Swift.Int) -> Swift.Int) -> ()"),
        .init(input: "$s4diff1hyyS2iYjdXEF", output: "diff.h(@differentiable (Swift.Int) -> Swift.Int) -> ()"),
        .init(input: "$s4diff1hyyS2iYjlXEF", output: "diff.h(@differentiable(_linear) (Swift.Int) -> Swift.Int) -> ()"),
        .init(input: "$s4test3fooyyS2f_SfYkztYjrXEF", output: "test.foo(@differentiable(reverse) (Swift.Float, inout @noDerivative Swift.Float) -> Swift.Float) -> ()"),
        .init(input: "$s4test3fooyyS2f_SfYkntYjrXEF", output: "test.foo(@differentiable(reverse) (Swift.Float, __owned @noDerivative Swift.Float) -> Swift.Float) -> ()"),
        .init(input: "$s4test3fooyyS2f_SfYktYjrXEF", output: "test.foo(@differentiable(reverse) (Swift.Float, @noDerivative Swift.Float) -> Swift.Float) -> ()"),
        .init(input: "$s4test3fooyyS2f_SfYktYaYbYjrXEF", output: "test.foo(@differentiable(reverse) @Sendable (Swift.Float, @noDerivative Swift.Float) async -> Swift.Float) -> ()"),
        .init(input: "$sScA", output: "Swift.Actor"),
        .init(input: "$sScGySiG", output: "Swift.TaskGroup<Swift.Int>"),
        .init(input: "$s4test10returnsOptyxycSgxyScMYccSglF", output: "test.returnsOpt<A>((@Swift.MainActor () -> A)?) -> (() -> A)?"),
        .init(input: "$sSvSgA3ASbIetCyyd_SgSbIetCyyyd_SgD", output: "(@escaping @convention(thin) @convention(c) (@unowned Swift.UnsafeMutableRawPointer?, @unowned Swift.UnsafeMutableRawPointer?, @unowned (@escaping @convention(thin) @convention(c) (@unowned Swift.UnsafeMutableRawPointer?, @unowned Swift.UnsafeMutableRawPointer?) -> (@unowned Swift.Bool))?) -> (@unowned Swift.Bool))?"),
        .init(input: "$s1t10globalFuncyyAA7MyActorCYiF", output: "t.globalFunc(isolated t.MyActor) -> ()"),
        .init(input: "$sSIxip6foobarP", output: "foobar in Swift.DefaultIndices.subscript : A"),
        .init(input: "$s13__lldb_expr_110$10016c2d8yXZ1B10$10016c2e0LLC", output: "__lldb_expr_1.(unknown context at $10016c2d8).(B in $10016c2e0)"),
        .init(input: "$s__TJO", output: "$s__TJO"),
        .init(input: "$s6Foobar7Vector2VAASdRszlE10simdMatrix5scale6rotate9translateSo0C10_double3x3aACySdG_SdAJtFZ0D4TypeL_aySd__GD", output: "MatrixType #1 in static (extension in Foobar):Foobar.Vector2<Swift.Double><A where A == Swift.Double>.simdMatrix(scale: Foobar.Vector2<Swift.Double>, rotate: Swift.Double, translate: Foobar.Vector2<Swift.Double>) -> __C.simd_double3x3"),
        .init(input: "$s17distributed_thunk2DAC1fyyFTE", output: "distributed thunk distributed_thunk.DA.f() -> ()"),
        .init(input: "$s16distributed_test1XC7computeyS2iFTF", output: "distributed accessor for distributed_test.X.compute(Swift.Int) -> Swift.Int"),
        .init(input: "$s27distributed_actor_accessors7MyActorC7simple2ySSSiFTETFHF", output: "accessible function runtime record for distributed accessor for distributed thunk distributed_actor_accessors.MyActor.simple2(Swift.Int) -> Swift.String"),
        .init(input: "$s1A3bar1aySSYt_tF", output: "A.bar(a: _const Swift.String) -> ()"),
        .init(input: "$s1t1fyyFSiAA3StrVcs7KeyPathCyADSiGcfu_SiADcfu0_33_556644b740b1b333fecb81e55a7cce98ADSiTf3npk_n", output: "function signature specialization <Arg[1] = [Constant Propagated KeyPath : _556644b740b1b333fecb81e55a7cce98<t.Str,Swift.Int>]> of implicit closure #2 (t.Str) -> Swift.Int in implicit closure #1 (Swift.KeyPath<t.Str, Swift.Int>) -> (t.Str) -> Swift.Int in t.f() -> ()"),
        .init(input: "$s21back_deploy_attribute0A12DeployedFuncyyFTwb", output: "back deployment thunk for back_deploy_attribute.backDeployedFunc() -> ()"),
        .init(input: "$s21back_deploy_attribute0A12DeployedFuncyyFTwB", output: "back deployment fallback for back_deploy_attribute.backDeployedFunc() -> ()"),
        .init(input: "$s4test3fooyyAA1P_px1TRts_XPlF", output: "test.foo<A>(any test.P<Self.T == A>) -> ()"),
        .init(input: "$s4test3fooyyAA1P_pSS1TAaCPRts_Si1UAERtsXPF", output: "test.foo(any test.P<Self.test.P.T == Swift.String, Self.test.P.U == Swift.Int>) -> ()"),
        .init(input: "$s4test3FooVAAyyAA1P_pF", output: "test.Foo.test(test.P) -> ()"),
        .init(input: "$sxxxIxzCXxxxesy", output: "$sxxxIxzCXxxxesy"),
        .init(input: "$Sxxx_x_xxIxzCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC$x", output: "$Sxxx_x_xxIxzCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC$x"),
        .init(input: "$sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTATQ0_", output: "(1) await resume partial function for partial apply forwarder for reabstraction thunk helper <A, B where A: Swift.Sendable, B == Swift.Never> from @escaping @callee_guaranteed @Sendable @async () -> (@out A) to @escaping @callee_guaranteed @async () -> (@out A, @error @owned Swift.Error)"),
        .init(input: "$sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTQ0_", output: "(1) await resume partial function for reabstraction thunk helper <A, B where A: Swift.Sendable, B == Swift.Never> from @escaping @callee_guaranteed @Sendable @async () -> (@out A) to @escaping @callee_guaranteed @async () -> (@out A, @error @owned Swift.Error)"),
        .init(input: "$sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTY0_", output: "(1) suspend resume partial function for reabstraction thunk helper <A, B where A: Swift.Sendable, B == Swift.Never> from @escaping @callee_guaranteed @Sendable @async () -> (@out A) to @escaping @callee_guaranteed @async () -> (@out A, @error @owned Swift.Error)"),
        .init(input: "$sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTY_", output: "(0) suspend resume partial function for reabstraction thunk helper <A, B where A: Swift.Sendable, B == Swift.Never> from @escaping @callee_guaranteed @Sendable @async () -> (@out A) to @escaping @callee_guaranteed @async () -> (@out A, @error @owned Swift.Error)"),
        .init(input: "$sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTQ12_", output: "(13) await resume partial function for reabstraction thunk helper <A, B where A: Swift.Sendable, B == Swift.Never> from @escaping @callee_guaranteed @Sendable @async () -> (@out A) to @escaping @callee_guaranteed @async () -> (@out A, @error @owned Swift.Error)"),
        .init(input: "$s7Library3fooyyFTwS", output: "#_hasSymbol query for Library.foo() -> ()"),
        .init(input: "$s7Library5KlassCTwS", output: "#_hasSymbol query for Library.Klass"),
        .init(input: "$s14swift_ide_test14myColorLiteral3red5green4blue5alphaAA0E0VSf_S3ftcfm", output: "swift_ide_test.myColorLiteral(red: Swift.Float, green: Swift.Float, blue: Swift.Float, alpha: Swift.Float) -> swift_ide_test.Color"),
        .init(input: "$s14swift_ide_test10myFilenamexfm", output: "swift_ide_test.myFilename : A"),
        .init(input: "$s9MacroUser13testStringify1a1bySi_SitF9stringifyfMf1_", output: "freestanding macro expansion #3 of stringify in MacroUser.testStringify(a: Swift.Int, b: Swift.Int) -> ()"),
        .init(input: "$s9MacroUser016testFreestandingA9ExpansionyyF4Foo3L_V23bitwidthNumberedStructsfMf_6methodfMu0_", output: "unique name #2 of method in freestanding macro expansion #1 of bitwidthNumberedStructs in Foo3 #1 in MacroUser.testFreestandingMacroExpansion() -> ()"),
        .init(input: "@__swiftmacro_1a13testStringifyAA1bySi_SitF9stringifyfMf_", output: "freestanding macro expansion #1 of stringify in a.testStringify(a: Swift.Int, b: Swift.Int) -> ()"),
        .init(input: "@__swiftmacro_18macro_expand_peers1SV1f20addCompletionHandlerfMp_", output: "peer macro @addCompletionHandler expansion #1 of f in macro_expand_peers.S"),
        .init(input: "@__swiftmacro_9MacroUser16MemberNotCoveredV33_4361AD9339943F52AE6186DD51E04E91Ll0dE0fMf0_", output: "freestanding macro expansion #2 of NotCovered(in _4361AD9339943F52AE6186DD51E04E91) in MacroUser.MemberNotCovered"),
        .init(input: "$sxSo8_NSRangeVRlzCRl_Cr0_llySo12ModelRequestCyxq_GIsPetWAlYl_TC", output: "coroutine continuation prototype for @escaping @convention(thin) @convention(witness_method) @yield_once <A, B where A: AnyObject, B: AnyObject> @substituted <A> (@inout A) -> (@yields @inout __C._NSRange) for <__C.ModelRequest<A, B>>"),
        .init(input: "$SyyySGSS_IIxxxxx____xsIyFSySIxx_@xIxx____xxI", output: "$SyyySGSS_IIxxxxx____xsIyFSySIxx_@xIxx____xxI"),
        .init(input: "$s12typed_throws15rethrowConcreteyyAA7MyErrorOYKF", output: "typed_throws.rethrowConcrete() throws(typed_throws.MyError) -> ()"),
        .init(input: "$s3red3use2fnySiyYAXE_tF", output: "red.use(fn: @isolated(any) () -> Swift.Int) -> ()"),
        .init(input: "$s4testAAyAA5KlassC_ACtACnYTF", output: "test.test(__owned test.Klass) -> sending (test.Klass, test.Klass)"),
        .init(input: "$s5test24testyyAA5KlassCnYuF", output: "test2.test(sending __owned test2.Klass) -> ()"),
        .init(input: "$s7ElementSTQzqd__s5Error_pIgnrzo_ABqd__sAC_pIegnrzr_SlRzr__lTR", output: "reabstraction thunk helper <A><A1 where A: Swift.Collection> from @callee_guaranteed (@in_guaranteed A.Swift.Sequence.Element) -> (@out A1, @error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed A.Swift.Sequence.Element) -> (@out A1, @error @out Swift.Error)"),
        .init(input: "$sS3fIedgyywTd_D", output: "@escaping @differentiable @callee_guaranteed (@unowned Swift.Float, @unowned @noDerivative sending Swift.Float) -> (@unowned Swift.Float)"),
        .init(input: "$sS3fIedgyyTd_D", output: "@escaping @differentiable @callee_guaranteed (@unowned Swift.Float, @unowned sending Swift.Float) -> (@unowned Swift.Float)"),
        .init(input: "$s4testA2A5KlassCyYTF", output: "test.test() -> sending test.Klass"),
        .init(input: "$s4main5KlassCACYTcMD", output: "demangling cache variable for type metadata for (main.Klass) -> sending main.Klass"),
        .init(input: "$s4null19transferAsyncResultAA16NonSendableKlassCyYaYTF", output: "null.transferAsyncResult() async -> sending null.NonSendableKlass"),
        .init(input: "$s4null16NonSendableKlassCIegHo_ACs5Error_pIegHTrzo_TR", output: "reabstraction thunk helper from @escaping @callee_guaranteed @async () -> (@owned null.NonSendableKlass) to @escaping @callee_guaranteed @async () -> sending (@out null.NonSendableKlass, @error @owned Swift.Error)"),
        .init(input: "$sSRyxG15Synchronization19AtomicRepresentableABRi_zrlMc", output: "protocol conformance descriptor for < where A: ~Swift.Copyable> Swift.UnsafeBufferPointer<A> : Synchronization.AtomicRepresentable in Synchronization"),
        .init(input: "$sSRyxG15Synchronization19AtomicRepresentableABRi0_zrlMc", output: "protocol conformance descriptor for < where A: ~Swift.Escapable> Swift.UnsafeBufferPointer<A> : Synchronization.AtomicRepresentable in Synchronization"),
        .init(input: "$sSRyxG15Synchronization19AtomicRepresentableABRi1_zrlMc", output: "protocol conformance descriptor for < where A: ~Swift.<bit 2>> Swift.UnsafeBufferPointer<A> : Synchronization.AtomicRepresentable in Synchronization"),
        .init(input: "$s23variadic_generic_opaque2G2VyAA2S1V_AA2S2VQPGAA1PHPAeA1QHPyHC_AgaJHPyHCHX_HC", output: "concrete protocol conformance variadic_generic_opaque.G2<Pack{variadic_generic_opaque.S1, variadic_generic_opaque.S2}> to protocol conformance ref (type's module) variadic_generic_opaque.P with conditional requirements: (pack protocol conformance (concrete protocol conformance variadic_generic_opaque.S1 to protocol conformance ref (type's module) variadic_generic_opaque.Q, concrete protocol conformance variadic_generic_opaque.S2 to protocol conformance ref (type's module) variadic_generic_opaque.Q))"),
        .init(input: "$s9MacroUser0023macro_expandswift_elFCffMX436_4_23bitwidthNumberedStructsfMf_", output: "freestanding macro expansion #1 of bitwidthNumberedStructs in module MacroUser file macro_expand.swift line 437 column 5"),
        .init(input: "$sxq_IyXd_D", output: "@callee_unowned (@in_cxx A) -> (@unowned B)"),
        .init(input: "$s2hi1SV1iSivx", output: "hi.S.i.modify2 : Swift.Int"),
        .init(input: "$s2hi1SV1iSivy", output: "hi.S.i.read2 : Swift.Int"),
        .init(input: "$s2hi1SVIetMIy_TC", output: "coroutine continuation prototype for @escaping @convention(thin) @convention(method) @yield_once_2 (@unowned hi.S) -> ()"),
        .init(input: "$s4mainAAyyycAA1CCFTTI", output: "identity thunk of main.main(main.C) -> () -> ()"),
        .init(input: "$s4mainAAyyycAA1CCFTTH", output: "hop to main actor thunk of main.main(main.C) -> () -> ()"),
        .init(input: "$s4main4SlabVy$1_SiG", output: "main.Slab<2, Swift.Int>"),
        .init(input: "$s$n3_SSBV", output: "Builtin.FixedArray<-4, Swift.String>"),
        .init(input: "$s3red7MyActorC3runyxxyYaKACYcYTXEYaKlFZ", output: "static red.MyActor.run<A>(@red.MyActor () async throws -> sending A) async throws -> A"),
        .init(input: "$s3red7MyActorC3runyxxyYaKYAYTXEYaKlFZ", output: "static red.MyActor.run<A>(@isolated(any) () async throws -> sending A) async throws -> A"),
        .init(input: "$s7ToolKit10TypedValueOACs5Error_pIgHTnTrzo_A2CsAD_pIegHiTrzr_TR", output: "reabstraction thunk helper from @callee_guaranteed @async (@in_guaranteed sending ToolKit.TypedValue) -> sending (@out ToolKit.TypedValue, @error @owned Swift.Error) to @escaping @callee_guaranteed @async (@in sending ToolKit.TypedValue) -> (@out ToolKit.TypedValue, @error @out Swift.Error)"),
        .init(input: "$s16sending_mangling16NonSendableKlassCACIegTiTr_A2CIegTxTo_TR", output: "reabstraction thunk helper from @escaping @callee_guaranteed (@in sending sending_mangling.NonSendableKlass) -> sending (@out sending_mangling.NonSendableKlass) to @escaping @callee_guaranteed (@owned sending sending_mangling.NonSendableKlass) -> sending (@owned sending_mangling.NonSendableKlass)"),
        .init(input: "$SSSTf4pd44444_pf", output: "function signature specialization <Arg[0] = [Constant Propagated Float : 44444], Return = > of Swift.String"),
        .init(input: "_$s15raw_identifiers0020foospace_liaADEDGcjayyF", output: "raw_identifiers.`foo\u{A0}space`() -> ()"),
        .init(input: "_$s15raw_identifiers0018_3times_pgaIGJCFbhayyF", output: "raw_identifiers.`3\u{A0}times`() -> ()"),
        .init(input: "_$s15raw_identifiers0019test_yeaIIBCEapkagayyF", output: "raw_identifiers.`test\u{A0}+`() -> ()"),
        .init(input: "_$s15raw_identifiers0020pathfoo_yuEHaaCiJskayyF", output: "raw_identifiers.`path://foo`() -> ()"),
        .init(input: "_$s15raw_identifiers10FontWeightO009_100_FpEpdyyFZ", output: "static raw_identifiers.FontWeight.`100`() -> ()"),
        .init(input: "$sBAIgHgIL_BAIegHgIL_TR", output: "reabstraction thunk helper from @callee_guaranteed @async (@guaranteed Builtin.ImplicitActor) -> () to @escaping @callee_guaranteed @async (@guaranteed Builtin.ImplicitActor) -> ()"),
        .init(input: "$sIeg_BAIegHgIL_TR", output: "reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_guaranteed @async (@guaranteed Builtin.ImplicitActor) -> ()"),
    ]
}
